/**
 * Nickname word banks for Bocchi's nickname generator
 * These provide building blocks and style examples for AI generation
 */

export const FIRST_WORDS = [
  "Captain",
  "Chief",
  "Professor",
  "Lord",
  "Dr",
  "General",
  "Master",
  "King",
  "Queen",
  "Duke",
  "Baron",
  "Sir",
  "Madam",
  "Lady",
  "Arch",
  "Grand",
  "Supreme",
  "Ultra",
  "Mega",
  "Super",
  "Prime",
  "Alpha",
  "Beta",
  "Omega",
  "Neo",
  "Cyber",
  "Digital",
  "Quantum",
  "Cosmic",
  "Galactic",
  "Interstellar",
  "Void",
  "Eternal",
  "Infinite",
  "Chaos",
  "Doom",
  "Dark",
  "Shadow",
  "Night",
  "Midnight",
  "Twilight",
  "Dawn",
  "Solar",
  "Lunar",
  "Stellar",
  "Celestial",
  "Astral",
  "Mystic",
  "Arcane",
  "Ancient",
  "Eldritch",
  "Cursed",
  "Blessed",
  "Holy",
  "Divine",
  "Sacred",
  "Profane",
  "Wicked",
  "Vile",
  "Foul",
  "Gross",
  "Sick",
  "Ill",
  "Toxic",
  "Radioactive",
  "Nuclear",
  "Atomic",
  "Molecular",
  "Cellular",
  "Genetic",
  "Bio",
  "Nano",
  "Micro",
  "Macro",
  "Giga",
  "Tera",
  "Peta",
  "Exa",
  "Zetta",
  "Yotta",
  "Mecha",
  "Robo",
  "Tech",
  "Cyborg",
  "Android",
  "Synth",
  "Virtual",
  "Augmented",
  "Enhanced",
  "Modified",
  "Mutated",
  "Evolved",
  "Devolved",
  "Regressed",
  "Transcended",
  "Ascended",
  "Descended",
  "Fallen",
  "Risen",
  "Awakened",
  "Enlightened",
  "Illuminated",
  "Radiant",
  "Luminous",
  "Brilliant",
  "Shining",
  "Glowing",
  "Burning",
  "Flaming",
  "Scorching",
  "Blazing",
  "Freezing",
  "Chilling",
  "Icy",
  "Frost",
  "Glacial",
  "Arctic",
  "Antarctic",
  "Tropical",
  "Equatorial",
  "Temperate",
  "Polar",
  "Desert",
  "Jungle",
  "Forest",
  "Ocean",
  "Marine",
  "Aquatic",
  "Terrestrial",
  "Aerial",
  "Atmospheric",
  "Stratospheric",
  "Tropospheric",
  "Ionospheric",
  "Exospheric",
  "Orbital",
  "Planetary",
  "Solar",
  "Lunar",
  "Martian",
  "Venusian",
  "Jovian",
  "Saturnian",
  "Uranian",
  "Neptunian",
  "Plutonian",
  "Galactic",
  "Universal",
  "Multiversal",
  "Omniversal",
  "Dimensional",
  "Interdimensional",
  "Transdimensional",
  "Hyperdimensional",
  "Paradimensional",
  "Metadimensional",
  " extradimensional",
  "Ultradimensional",
  "Megadimensional",
  "Gigadimensional",
  "Teradimensional",
  "Petadimensional",
  "Exadimensional",
  "Zettadimensional",
  "Yottadimensional"
];

export const SECOND_WORDS = [
  "Dih",
  "Yapper",
  "Dumguru",
  "Bonk",
  "Goober",
  "Braincell",
  "Smoothbrain",
  "Cringe",
  "Based",
  "Redpilled",
  "Bluepilled",
  "Basedpilled",
  "Cringe lord",
  "Based god",
  "Sigma",
  "Alpha",
  "Beta",
  "Omega",
  "Delta",
  "Gamma",
  "Epsilon",
  "Zeta",
  "Eta",
  "Theta",
  "Iota",
  "Kappa",
  "Lambda",
  "Mu",
  "Nu",
  "Xi",
  "Omicron",
  "Pi",
  "Rho",
  "Sigma",
  "Tau",
  "Upsilon",
  "Phi",
  "Chi",
  "Psi",
  "Omega",
  "Chad",
  "Virgin",
  "Simp",
  "Incel",
  "Normie",
  "NPC",
  "Gamer",
  "Stream sniper",
  "Tryhard",
  "Sweat",
  "Noob",
  "Newbie",
  "Scrub",
  "Casual",
  "Hardcore",
  "Pro",
  "Elite",
  "Master",
  "Grandmaster",
  "Challenger",
  "Diamond",
  "Platinum",
  "Gold",
  "Silver",
  "Bronze",
  "Iron",
  "Unranked",
  "Smurf",
  "Booster",
  "Thrower",
  "Griefer",
  "Troll",
  "Flamer",
  "Toxic",
  "Salty",
  "Rage quitter",
  "Leaver",
  "AFK",
  "Idle",
  "Bot",
  "Hack",
  "Cheater",
  "Exploiter",
  "Glitcher",
  "Lagger",
  "Ping abuser",
  "Packet loss",
  "Rubber banding",
  "Desync",
  "Hitbox",
  "Hitreg",
  "Frametime",
  "FPS",
  "Refresh rate",
  "Response time",
  "Input lag",
  "Screen tearing",
  "Vsync",
  "Gsync",
  "Freesync",
  "HDR",
  "4K",
  "1440p",
  "1080p",
  "720p",
  "480p",
  "360p",
  "240p",
  "144p",
  "Pixel art",
  "Voxel",
  "Polygon",
  "Mesh",
  "Texture",
  "Shader",
  "Render",
  "Lighting",
  "Shadow",
  "Reflection",
  "Refraction",
  "Diffraction",
  "Dispersion",
  "Scattering",
  "Absorption",
  "Emission",
  "Radiation",
  "Conduction",
  "Convection",
  "Advection",
  "Diffusion",
  "Osmosis",
  "Filtration",
  "Distillation",
  "Extraction",
  "Purification",
  "Contamination",
  "Pollution",
  "Toxicity",
  "Hazard",
  "Danger",
  "Risk",
  "Threat",
  "Menace",
  "Peril",
  "Jeopardy",
  "Precarious",
  "Uncertain",
  "Unstable",
  "Volatile",
  "Explosive",
  "Combustible",
  "Flammable",
  "Inflammable",
  "Corrosive",
  "Caustic",
  "Acidic",
  "Basic",
  "Alkaline",
  "Neutral",
  "pH",
  "Ion",
  "Electron",
  "Proton",
  "Neutron",
  "Atom",
  "Molecule",
  "Compound",
  "Mixture",
  "Solution",
  "Suspension",
  "Colloid",
  "Emulsion",
  "Foam",
  "Gel",
  "Solid",
  "Liquid",
  "Gas",
  "Plasma",
  "Bose-Einstein condensate",
  "Supercritical fluid",
  "Supersolid",
  "Rydberg matter",
  "Photonic matter",
  "Time crystal",
  "Quantum foam",
  "String",
  "Brane",
  "Membrane",
  "Dimension",
  "Universe",
  "Multiverse",
  "Omniverse",
  "Cosmos",
  "Space",
  "Time",
  "Spacetime",
  "Gravity",
  "Electromagnetism",
  "Weak force",
  "Strong force",
  "Dark matter",
  "Dark energy",
  "Antimatter",
  "Negative matter",
  "Exotic matter",
  "Strange matter",
  "Quark matter",
  "Neutronium",
  "Degenerate matter",
  "Plasma",
  "Fusion",
  "Fission",
  "Annihilation",
  "Pair production",
  "Beta decay",
  "Alpha decay",
  "Gamma decay",
  "Radioactive decay",
  "Half-life",
  "Carbon dating",
  "Radiometric dating",
  "Nuclear physics",
  "Particle physics",
  "Quantum physics",
  "Classical physics",
  "Relativity",
  "Special relativity",
  "General relativity",
  "Quantum mechanics",
  "Quantum field theory",
  "String theory",
  "M-theory",
  "Loop quantum gravity",
  "Causal dynamical triangulation",
  "Causal sets",
  "Twistor theory",
  "Noncommutative geometry",
  "Emergent gravity",
  "Entropic gravity",
  "Modified Newtonian dynamics",
  "Tensor-vector-scalar gravity",
  "Scalar-tensor gravity",
  "Brans-Dicke theory",
  "Einstein-Cartan theory",
  "Teleparallel gravity",
  "F(R) gravity",
  "Gauss-Bonnet gravity",
  "Horndeski theory",
  "Galileon theory",
  "Massive gravity",
  "Bimetric gravity",
  "Nonsymmetric gravitational theory",
  "Metric-affine gravity",
  "Poincaré gauge theory",
  "Einstein-aether theory",
  "Tensor-vector-scalar theory",
  "Scalar-tensor-vector theory",
  "Bimetric theory",
  "Multimetric gravity",
  "Polymetric gravity",
  "Omnimetric gravity",
  "Ultrametric gravity",
  "Megametric gravity",
  "Gigametric gravity",
  "Terametric gravity",
  "Petametric gravity",
  "Exametric gravity",
  "Zettametric gravity",
  "Yottametric gravity"
];

export const NICKNAME_TITLES = [
  "Sensei",
  "Senpai",
  "Kohai",
  "Sama",
  "Kun",
  "Chan",
  "San",
  "Dono",
  "Hime",
  "Ouji",
  "Heika",
  "Kakka",
  "Daitoku",
  "Taicho",
  "Fukucho",
  "Chui",
  "Gunso",
  "Junsa",
  "Keiji",
  "Sotsucho",
  "Taii",
  "Shoi",
  "Chui",
  "Nito",
  "Rikugun",
  "Kaigun",
  "Kuugun",
  "Rikujieitai",
  "Kaigieitai",
  "Kuujieitai",
  "Jieitai",
  "Guntai",
  "Kaigun",
  "Kuugun",
  "Rikugun",
  "Jieitai",
  "SDF",
  "JSDF",
  "JGSDF",
  "JMSDF",
  "JASDF",
  "USAF",
  "USN",
  "USMC",
  "US Army",
  "USCG",
  "NATO",
  "UN",
  "EU",
  "ASEAN",
  "AU",
  "OAS",
  "Arab League",
  "OIC",
  "CIS",
  "SCO",
  "BRICS",
  "G7",
  "G20",
  "G77",
  "NAM",
  "OECD",
  "WTO",
  "WHO",
  "UNESCO",
  "UNICEF",
  "UNHCR",
  "WFP",
  "FAO",
  "ILO",
  "IMO",
  "ICAO",
  "ITU",
  "UPU",
  "WMO",
  "WIPO",
  "IAEA",
  "CTBTO",
  "OPCW",
  "ICC",
  "ICJ",
  "PCA",
  "ITLOS",
  "ISA",
  "WTO",
  "UNWTO",
  "UNCTAD",
  "UNDP",
  "UNEP",
  "UNFPA",
  "UN-Habitat",
  "UN Women",
  "UNAIDS",
  "UNOPS",
  "UNRWA",
  "UNIDO",
  "UNODC",
  "UNWTO",
  "UNU",
  "UNSSC",
  "UNIDIR",
  "UNITAR",
  "UNRISD",
  "UNU-INRA",
  "UNU-WIDER",
  "UNU-MERIT",
  "UNU-FLORES",
  "UNU-CRIS",
  "UNU-IAS",
  "UNU-BIOLAC",
  "UNU-INWEH",
  "UNU-EHS",
  "UNU-IIGH",
  "UNU-IIST",
  "UNU-IIST",
  "UNU-IIST",
  "UNU-IIST"
];

export const NICKNAME_ADJECTIVES = [
  "Supreme",
  "Ultimate",
  "Final",
  "Last",
  "First",
  "Original",
  "True",
  "Real",
  "Actual",
  "Genuine",
  "Authentic",
  "Legitimate",
  "Valid",
  "Verified",
  "Certified",
  "Approved",
  "Official",
  "Authorized",
  "Licensed",
  "Registered",
  "Documented",
  "Recorded",
  "Noted",
  "Marked",
  "Tagged",
  "Labeled",
  "Stamped",
  "Sealed",
  "Signed",
  "Endorsed",
  "Backed",
  "Supported",
  "Funded",
  "Sponsored",
  "Patronized",
  "Subsidized",
  "Financed",
  "Underwritten",
  "Guaranteed",
  "Warranted",
  "Assured",
  "Insured",
  "Protected",
  "Defended",
  "Guarded",
  "Shielded",
  "Covered",
  "Sheltered",
  "Housed",
  "Accommodated",
  "Lodged",
  "Quartered",
  "Stationed",
  "Posted",
  "Deployed",
  "Positioned",
  "Placed",
  "Located",
  "Situated",
  "Found",
  "Discovered",
  "Uncovered",
  "Revealed",
  "Exposed",
  "Shown",
  "Displayed",
  "Exhibited",
  "Presented",
  "Introduced",
  "Launched",
  "Started",
  "Begun",
  "Commenced",
  "Initiated",
  "Inaugurated",
  "Opened",
  "Unveiled",
  "Revealed",
  "Disclosed",
  "Divulged",
  "Leaked",
  "Exposed",
  "Uncovered",
  "Discovered",
  "Found",
  "Located",
  "Identified",
  "Recognized",
  "Acknowledged",
  "Accepted",
  "Admitted",
  "Allowed",
  "Permitted",
  "Authorized",
  "Enabled",
  "Empowered",
  "Licensed",
  "Qualified",
  "Eligible",
  "Suitable",
  "Fit",
  "Appropriate",
  "Proper",
  "Right",
  "Correct",
  "Accurate",
  "Precise",
  "Exact",
  "Specific",
  "Particular",
  "Special",
  "Unique",
  "Distinct",
  "Different",
  "Separate",
  "Individual",
  "Personal",
  "Private",
  "Secret",
  "Hidden",
  "Concealed",
  "Disguised",
  "Masked",
  "Camouflaged",
  "Blended",
  "Merged",
  "Combined",
  "Mixed",
  "Blended",
  "Fused",
  "Joined",
  "United",
  "Connected",
  "Linked",
  "Associated",
  "Related",
  "Affiliated",
  "Allied",
  "Partnered",
  "Collaborated",
  "Cooperated",
  "Worked",
  "Operated",
  "Functioned",
  "Performed",
  "Executed",
  "Carried out",
  "Implemented",
  "Enforced",
  "Applied",
  "Used",
  "Utilized",
  "Employed",
  "Deployed",
  "Exploited",
  "Leveraged",
  "Harnessed",
  "Wielded",
  "Brandished",
  "Flaunted",
  "Showed off",
  "Displayed",
  "Exhibited",
  "Demonstrated",
  "Illustrated",
  "Exemplified",
  "Represented",
  "Symbolized",
  "Signified",
  "Meant",
  "Intended",
  "Designed",
  "Planned",
  "Intended",
  "Aimed",
  "Targeted",
  "Focused",
  "Centered",
  "Concentrated",
  "Directed",
  "Guided",
  "Led",
  "Commanded",
  "Controlled",
  "Managed",
  "Administered",
  "Supervised",
  "Overseen",
  "Monitored",
  "Watched",
  "Observed",
  "Noticed",
  "Detected",
  "Perceived",
  "Sensed",
  "Felt",
  "Experienced",
  "Underwent",
  "Endured",
  "Suffered",
  "Bore",
  "Tolerated",
  "Accepted",
  "Acknowledged",
  "Recognized",
  "Admitted",
  "Confessed",
  "Revealed",
  "Disclosed",
  "Divulged",
  "Shared",
  "Communicated",
  "Conveyed",
  "Transmitted",
  "Sent",
  "Delivered",
  "Dispatched",
  "Shipped",
  "Transported",
  "Carried",
  "Brought",
  "Took",
  "Fetched",
  "Retrieved",
  "Recovered",
  "Reclaimed",
  "Regained",
  "Recaptured",
  "Repossessed",
  "Retaken",
  "Reacquired",
  "Reobtained",
  "Regathered",
  "Recollected",
  "Remembered",
  "Recalled",
  "Reminded",
  "Recounted",
  "Related",
  "Narrated",
  "Told",
  "Spoke",
  "Said",
  "Uttered",
  "Articulated",
  "Expressed",
  "Voiced",
  "Stated",
  "Declared",
  "Proclaimed",
  "Announced",
  "Pronounced",
  "Asserted",
  "Affirmed",
  "Confirmed",
  "Verified",
  "Validated",
  "Authenticated",
  "Certified",
  "Accredited",
  "Endorsed",
  "Approved",
  "Sanctioned",
  "Authorized",
  "Licensed",
  "Permitted",
  "Allowed",
  "Enabled",
  "Empowered",
  "Entitled",
  "Qualified",
  "Eligible",
  "Suitable",
  "Fit",
  "Proper",
  "Appropriate",
  "Right",
  "Correct",
  "Accurate",
  "Precise",
  "Exact",
  "Specific",
  "Particular",
  "Special",
  "Unique",
  "Distinct",
  "Different",
  "Separate",
  "Individual",
  "Personal",
  "Private",
  "Secret",
  "Hidden",
  "Concealed",
  "Disguised",
  "Masked",
  "Camouflaged",
  "Blended",
  "Merged",
  "Combined",
  "Mixed",
  "Blended",
  "Fused",
  "Joined",
  "United",
  "Connected",
  "Linked",
  "Associated",
  "Related",
  "Affiliated",
  "Allied",
  "Partnered",
  "Collaborated",
  "Cooperated",
  "Worked",
  "Operated",
  "Functioned",
  "Performed",
  "Executed",
  "Carried out",
  "Implemented",
  "Enforced",
  "Applied",
  "Used",
  "Utilized",
  "Employed",
  "Deployed",
  "Exploited",
  "Leveraged",
  "Harnessed",
  "Wielded",
  "Brandished",
  "Flaunted",
  "Showed off",
  "Displayed",
  "Exhibited",
  "Demonstrated",
  "Illustrated",
  "Exemplified",
  "Represented",
  "Symbolized",
  "Signified"
];

export const NICKNAME_NOUNS = [
  "Titan",
  "God",
  "Deity",
  "Divinity",
  "Angel",
  "Demon",
  "Spirit",
  "Ghost",
  "Phantom",
  "Specter",
  "Wraith",
  "Shade",
  "Shadow",
  "Reflection",
  "Echo",
  "Resonance",
  "Vibration",
  "Frequency",
  "Wave",
  "Particle",
  "Atom",
  "Molecule",
  "Compound",
  "Element",
  "Substance",
  "Material",
  "Matter",
  "Energy",
  "Force",
  "Power",
  "Strength",
  "Might",
  "Vigor",
  "Vitality",
  "Life",
  "Existence",
  "Being",
  "Entity",
  "Creature",
  "Organism",
  "Animal",
  "Beast",
  "Monster",
  "Fiend",
  "Devil",
  "Satan",
  "Lucifer",
  "Mephistopheles",
  "Beelzebub",
  "Asmodeus",
  "Baal",
  "Leviathan",
  "Behemoth",
  "Ziz",
  "Dragon",
  "Serpent",
  "Snake",
  "Viper",
  "Cobra",
  "Python",
  "Anaconda",
  "Boa",
  "Constrictor",
  "Rattlesnake",
  "Adder",
  "Asp",
  "Mamba",
  "Taipan",
  "Tiger snake",
  "Death adder",
  "Black mamba",
  "Green mamba",
  "King cobra",
  "Indian cobra",
  "Egyptian cobra",
  "Spitting cobra",
  "Tree cobra",
  "Forest cobra",
  "Water cobra",
  "Sea snake",
  "Krait",
  "Coral snake",
  "Sea krait",
  "Yellow-bellied sea snake",
  "Beaked sea snake",
  "Hook-nosed sea snake",
  "Spine-bellied sea snake",
  "Hardwicke's sea snake",
  "Shaw's sea snake",
  "Spectacled sea snake",
  "Turtle-headed sea snake",
  "Dwarf sea snake",
  "Slender sea snake",
  "Small-eyed sea snake",
  "Big-eyed sea snake",
  "Olive sea snake",
  "Grey sea snake",
  "Brown sea snake",
  "Black sea snake",
  "Yellow sea snake",
  "White sea snake",
  "Red sea snake",
  "Blue sea snake",
  "Green sea snake",
  "Purple sea snake",
  "Pink sea snake",
  "Orange sea snake",
  "Gold sea snake",
  "Silver sea snake",
  "Bronze sea snake",
  "Copper sea snake",
  "Iron sea snake",
  "Steel sea snake",
  "Lead sea snake",
  "Tin sea snake",
  "Zinc sea snake",
  "Aluminum sea snake",
  "Magnesium sea snake",
  "Calcium sea snake",
  "Sodium sea snake",
  "Potassium sea snake",
  "Lithium sea snake",
  "Rubidium sea snake",
  "Cesium sea snake",
  "Francium sea snake",
  "Beryllium sea snake",
  "Strontium sea snake",
  "Barium sea snake",
  "Radium sea snake",
  "Titanium sea snake",
  "Zirconium sea snake",
  "Hafnium sea snake",
  "Rutherfordium sea snake",
  "Vanadium sea snake",
  "Niobium sea snake",
  "Tantalum sea snake",
  "Dubnium sea snake",
  "Chromium sea snake",
  "Molybdenum sea snake",
  "Tungsten sea snake",
  "Seaborgium sea snake",
  "Manganese sea snake",
  "Technetium sea snake",
  "Rhenium sea snake",
  "Bohrium sea snake",
  "Iron sea snake",
  "Ruthenium sea snake",
  "Osmium sea snake",
  "Hassium sea snake",
  "Cobalt sea snake",
  "Rhodium sea snake",
  "Iridium sea snake",
  "Meitnerium sea snake",
  "Nickel sea snake",
  "Palladium sea snake",
  "Platinum sea snake",
  "Darmstadtium sea snake",
  "Copper sea snake",
  "Silver sea snake",
  "Gold sea snake",
  "Roentgenium sea snake",
  "Zinc sea snake",
  "Cadmium sea snake",
  "Mercury sea snake",
  "Copernicium sea snake",
  "Boron sea snake",
  "Aluminum sea snake",
  "Gallium sea snake",
  "Indium sea snake",
  "Thallium sea snake",
  "Nihonium sea snake",
  "Carbon sea snake",
  "Silicon sea snake",
  "Germanium sea snake",
  "Tin sea snake",
  "Lead sea snake",
  "Flerovium sea snake",
  "Nitrogen sea snake",
  "Phosphorus sea snake",
  "Arsenic sea snake",
  "Antimony sea snake",
  "Bismuth sea snake",
  "Moscovium sea snake",
  "Oxygen sea snake",
  "Sulfur sea snake",
  "Selenium sea snake",
  "Tellurium sea snake",
  "Polonium sea snake",
  "Livermorium sea snake",
  "Fluorine sea snake",
  "Chlorine sea snake",
  "Bromine sea snake",
  "Iodine sea snake",
  "Astatine sea snake",
  "Tennessine sea snake",
  "Helium sea snake",
  "Neon sea snake",
  "Argon sea snake",
  "Krypton sea snake",
  "Xenon sea snake",
  "Radon sea snake",
  "Oganesson sea snake"
];

// Discord nickname length limit is 32 characters
export const DISCORD_NICKNAME_MAX_LENGTH = 32;

// Maximum number of generation attempts before giving up
export const NICKNAME_MAX_GENERATION_ATTEMPTS = 10;
